//go:build ignore

package main

import (
	"fmt"
	"math"
	"os"
)

func main() {
	f, err := os.Create("srgb_lut.go")
	if err != nil {
		panic(err)
	}
	defer f.Close() //nolint:errcheck

	fmt.Fprintln(f, "// Code generated by srgb_lut_generator.go; DO NOT EDIT.")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "//go:generate go run srgb_lut_generator.go")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "package blurhash")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "var sRGBToLinearLUT = [256]float64{")

	for i := 0; i < 256; i++ {
		v := float64(i) / 255
		var linear float64
		if v <= 0.04045 {
			linear = v / 12.92
		} else {
			linear = math.Pow((v+0.055)/1.055, 2.4)
		}
		fmt.Fprintf(f, "\t%.17g,\n", linear)
	}

	fmt.Fprintln(f, "}")
}
